### ISSUE TITLE
[Bug] Internal path `BUILT-IN` not listed in editor while exists

### ISSUE THREAD

**Issue by YuLun-bili** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#511] opened 2024-02-02 20:57 UTC
### Describe the bug

<img src="https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/ce7186ca-469c-49e5-a9f2-3e3f34ae29e5" width="100px">
<img src="https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/assets/70589524/e7bf9add-a5e2-477b-b625-20afa9250f1b" width="140px">

As shown in screenshot, the mini file browser drop down list doesn't include `BUILT-IN` but one can manually enter that path and browse contents inside

### Steps to reproduce the behavior

go to editor, select any path and see if can find `BUILT-IN` in drop down list

### Expected behavior

`BUILT-IN` listed in drop down

### Environment

- Teardown Version 1.5.3
- OS: Win 11

### Additional context

I know it's a new thing so maybe it just not done yet, but anyway :)

**Comment by Gregory-Gregory** [comment] 2024-02-05 05:11
Hello @YuLun-bili,

Thank you for your report.

We have reported this issue to the QA team for the investigation.
If any additional details regarding this question are needed, we will contact you again in this discussion.

**Comment by Gregory-Gregory** [comment] 2024-02-09 07:44
Hi @YuLun-bili,

The QA team has not been able to reproduce this issue with the mentioned steps.

If you still experience this, can you please share a video? Or please clarify what path you have this issue with.

Thank you!

**Comment by Please-Pick-a-Name** [comment] 2024-02-09 23:13
> Hi @YuLun-bili,
> 
> The QA team has not been able to reproduce this issue with the mentioned steps.
> 
> If you still experience this, can you please share a video? Or please clarify what path you have this issue with.
> 
> Thank you!

Is the QA team testing the public branch 1.5.3? since i can see [vox], [voxbox], [script], etc all doesnt show the built-in prefix unless you type it in

**Comment by Gregory-Gregory** [comment] 2024-02-09 23:48
@Please-Pick-a-Name Thank you for mentioning this. I have asked the team for more information.

**Comment by Gregory-Gregory** [comment] 2024-02-13 01:13
@YuLun-bili @Please-Pick-a-Name,

The team clarified that this issue will be fixed in one of the upcoming patches.

**Comment by Please-Pick-a-Name** [comment] 2024-03-06 05:08
fixed in 1.5.4 on experimental branch

**Closed as completed** 2024-04-17 13:58 UTC
Labels: bug, dev/resolved, type/editor
