### ISSUE TITLE
[Bug] Game crashing when boat is completely destroyed when player is inside.

### ISSUE THREAD

**Issue by GGProGaming** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#7] opened 2021-03-16 16:59 UTC
**Describe the bug**
Placing Bombs on the little wooden boat and then entering the boat will cause the game to crash.

**To Reproduce**
1. Go to Hollowrock in the sandbox or any other map that has the small wooden boat that is tied to the dock.
2. Place bombs on the boat
3. Enter the boat
4. Game crashes

**Expected behavior**
Game shouldn't crash

**System Info**
 - Teardown Version: 0.6.2 (patch 1) 
 - OS: [e.g. Windows/Linux] N/A
 - GPU: N/A
 - Graphics driver version: N/A
 - CPU: N/A

**Additional context**
None

**Comment by ss-gnalvesteffer** [comment] 2021-04-05 15:52
@CoolJWB,

@Thomasims pointed out that this issue may be a duplicate of this issue, and I think this observation may provide additional insight into this problem:
https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/25

**Comment by tuxedolabs** [comment] 2021-04-12 12:30
Fixed in 0.7.0

**Closed** 2021-04-19 07:41 UTC
Labels: dev/resolved, issue/bug, tag/type-engine
