### ISSUE TITLE
[bug] certain tool mods causing excessive pag

### ISSUE THREAD

**Issue by SearMr-cool** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#411] opened 2023-10-29 00:51 UTC
### Describe the bug

It seems that certain weapons heavily lag the game for no apparent reason (I didn't notice this in the previous version) the only correlation I can draw between then is that they all seem to be more reflective compared to the other tools, here is a list of mods that cause the lag for me:
Aug
Ballistic shield
Fim-92 stinger
High frequency blade
Atomic ac-130

### Steps to reproduce the behavior

1. Download and enable one of the mods listed (make sure your own experimental branch
2. Go into a world and equip the tool and the whole game lags 

### Expected behavior

No major change in fps

### Environment

- Teardown Version: 1.5.0 experimental
- OS: Windows
- GPU: rtx 3060 mobile gpu
- Graphics driver version: 542.92
- CPU: Ryzen 7 5800h

**Comment by YuLun-bili** [comment] 2024-05-08 10:41
Well it's very likely that these lag are caused by mods rather than game itself and I'd suggest reporting this to mod creator. If you've disabled all mods and still experiencing lag then it would be game's issue. Closing.

**Closed as completed by YuLun-bili** 2024-05-08 10:41 UTC
Labels: bug
