### ISSUE TITLE
[Bug] Editor - While allowing for different "snap" options, still does not honor them in the text fields

### ISSUE THREAD

**Issue by RavMahov** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#29] opened 2021-04-12 10:55 UTC
**Describe the bug**
The Editor, while allowing for different "snap" options, still does not honor them in the text field, so once you click "apply", all your precise positioning work is ruined (no matter if you touched position field or not).

**To Reproduce**
1. Go into the Editor
2. Set Snap settings to something around 0.01 for position (for a good measure)
3. Try writing the position that should be honored (move the thing by 0.03)
4. Press Apply
5. Position coordinates will get truncated to whatever text field was set to (I think it also happens with rotation, worth checking)
6. Use gizmos to move your stuff with such precision (it really is useful if you want the things snapped to each other and they're rotated by non-90 degree amount)
7. Press Apply and see your positioning ruined
8. Writhe in pain at the thought of positioning things with such precision only to have to redo it since you wanted to touch another field

**Expected behavior**
I don't see why Apply button (or modification of the text field) should ignore the snap settings (by using defaults) so I consider it a bug.

**Screenshots**
Video could help, screenshots probably won't

**Environment**
 - Teardown Version 0.6.2 (patch 1)
 - OS: Windows
 - GPU: GTX 1080Ti
 - Graphics driver version: shouldn't matter
 - CPU: Intel i5 4670K

**Additional context**
It really is a valid use case to use such precision, especially when positioning stuff that's rotated by non-90 degree amount. I thought that snap settings were introduced not to be broken by modification of text field or pressing Apply button

**Comment by tuxedolabs** [comment] 2021-04-12 11:58
This is the intended behavior. Snap only affects mouse drag for both move and rotate.

**Comment by ss-gnalvesteffer** [comment] 2021-04-12 15:07
Closing this issue as it sounds like this will not be worked on according to @tuxedolabs’ comment. Please reopen if this is not the case.

**Comment by RavMahov** [comment] 2021-04-12 21:23
Maybe I didn't make myself clear. Apply button is required for other things too, so if I "pose" something with gizmos and then don't want to touch it, but must apply a tag or value or something, then press Apply, should it break my position too? :o Is my only option to go into xml file and change it?

Example would be those 4 screens connected on 2 edges each, but angled screens also required higher precision
![image](https://user-images.githubusercontent.com/9891611/114464420-085c9280-9be6-11eb-8f5e-fb15e41fd499.png)

**Comment by tuxedolabs** [comment] 2021-04-13 06:25
Sorry, I misunderstand the issue. This has nothing to do with snap. There should be an automatic rounding to the closest 0.01 voxel. There was a bug causing that rounding to 0.1. This should be fixed in 0.7.0

**Comment by ss-gnalvesteffer** [comment] 2021-04-13 06:27
Re-opening due to previous comment.

**Closed** 2021-04-19 07:39 UTC
Labels: dev/resolved, issue/bug
