### ISSUE TITLE
[Bug] TV/PC picture gets moved away from TV/PC by snowballs

### ISSUE THREAD

**Issue by koinova** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#207] opened 2022-04-14 00:01 UTC
### Describe the bug

Throwing snowballs at either the flatscreen TV or the PC on the hub map causes their pictures to shift away from the actual object they're tied to.
The PC screen shifts towards the player, to the left and slightly down.
The TV screen shifts backwards into the wall and behind the TV panel itself.

The messed up PC screen
![20220414015044_1](https://user-images.githubusercontent.com/62450627/163288529-c2bb2dca-23e9-44f5-a670-518b248dcdde.jpg)

The TV image inside the (now broken) wall
![20220414012845_1](https://user-images.githubusercontent.com/62450627/163288569-0e813d71-015a-41ad-bb65-e2ce8187f060.jpg)

The front of the TV
![20220414014016_1](https://user-images.githubusercontent.com/62450627/163288609-4b17f3e0-0362-4c95-bee1-ce56036ec754.jpg)

### Steps to reproduce the behavior

1. Pick up snowballs on the outside of the LTS building
2. Go inside
3. Throw snowballs at the flatscreen TV or the PC screen
4. Watch the magic of floating pictures unfold in front of your eyes

### Expected behavior

Nothing, the picture should stay in the same place as normal.

### Environment

- Teardown Version: 0.9.6
- OS: Windows 10 Home, version 21H1
- GPU: NVIDIA GeForce GTX 980Ti
- Graphics driver version: 511.65
- CPU: Intel Core i7-6700k

**Comment by nooitaf** [comment] 2022-04-14 02:38
Duplicate of #204 and #195

**Closed as completed** 2022-04-14 17:56 UTC
Labels: bug, duplicate
