### ISSUE TITLE
[Feature] Add crash log

### ISSUE THREAD

**Issue by Zagdima** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#109] opened 2022-02-01 15:53 UTC
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

Please add special folder or smth so when game crash it can put crash log file there.

### Describe the solution you'd like

Adding ability to check wich is caused game crash, is it a empty vox, or incorrect prameters in editor.

### Describe alternatives you've considered

- add ability to open crash folder or crash log file.

**Comment by Thomasims** [comment] 2022-02-01 21:10
Duplicate of #51

**Closed by Thomasims** 2022-02-01 21:10 UTC
Labels: feature request
