### ISSUE TITLE
azerty layout not made for creative mode/creative mode keybinds not editable

### ISSUE THREAD

**Issue by krunkske** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#355] opened 2023-06-19 17:14 UTC
### Describe the bug

azerty layout not made for creative mode/creative mode keybinds not editable

### Steps to reproduce the behavior

see title

### Expected behavior

to be able to change the keybinds

### Environment

- Teardown Version e.g. 1.4.0
- OS: Windows 11 64 bit
- GPU: Nvidia GeForce 1650
- Graphics driver version: not relevant 
- CPU: AMD Ryzen 7 3750H

**Comment by Thomasims** [comment] 2023-06-19 17:16
Duplicate of #353

**Closed as completed by Thomasims** 2023-06-19 17:16 UTC
Labels: bug, duplicate

**Comment by krunkske** [comment] 2023-06-19 17:18
Did not see that one. Sorry for the duplicate post.
