### ISSUE TITLE
a

### ISSUE THREAD

**Issue by marioluigicom1234** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#347] opened 2023-06-03 21:38 UTC
### Describe the bug

there's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probably

### Steps to reproduce the behavior

2. Click on '..there's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probably..'
there's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probably

### Expected behavior

there's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probablythere's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probably

### Environment

- Teardown Version [e.g. 0.6.2 (patch 1) -- this is visible at the bottom-right of the main menu]
- OS: [e.g. Windows/Linux]
- GPU:
- Graphics driver version:
- CPU:
there's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probably

### Additional context

there's an issue with the game where things won't load properly in items won't spawn in properly maybe you could fix it probably

**Comment by Please-Pick-a-Name** [comment] 2023-06-03 22:44
cannot recreate, closing issue @Thomasims

**Comment by Thomasims** [comment] 2023-06-04 16:51
It's hard to tell what the issue actually is since the template was not properly filled in but it sounds like the problem caused by having lower specs than minimal recommended.
If that is not the problem I suggest you spend more time describing the issue so someone else actually has a chance of repeating it.

**Closed as completed by Thomasims** 2023-06-04 16:51 UTC
Labels: bug
