### ISSUE TITLE
[Bug] Falling off the map when you die can end in black screen

### ISSUE THREAD

**Issue by nooitaf** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#74] opened 2021-12-19 03:51 UTC
### Describe the bug

Edge case, but happened to me a few times (not in campain).
If you fall of the map while the death fade starts and you respawn faster then the fade is done, it will end in black screen

https://user-images.githubusercontent.com/1898194/146663170-f0175766-e9d1-4266-b2e8-aa55ef116cf1.mp4

.

### Steps to reproduce the behavior

1. Die and fall into oblivian at the same time
2. Fade to black starts
3. Autorespawn
4. Fade finishes
5. Black screen stays

### Expected behavior

Fade should reset/finish when respawning

### Environment

- Teardown Version 0.9.2
- OS: Linux
- GPU: gtx970
- CPU: i5

**Comment by tuxedolabs** [comment] 2022-02-07 08:47
We have a duplicate of this internally. I will take a look at it. Thanks for reporting!

**Closed by tuxedolabs** 2022-02-07 08:47 UTC
Labels: bug, dev/in progress, type/engine
