### ISSUE TITLE
[Feature] Get pbr + texture of voxel

### ISSUE THREAD

**Issue by FlorentP42** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#287] opened 2022-11-06 09:14 UTC
### Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.

`GetShapeMaterialAtIndex/Position()` is great to scan the environment, but some information are missing to be able to perfectly replicate a voxel, expecially: the pbr values (roughness, metallic, emissive, shiny), and the texture.

### Describe the solution you'd like

Either add those to the return values of `GetShapeMaterialAtIndex/Position()`, or make dedicated functions for that.

### Describe alternatives you've considered

No alternative

### Additional context

Note that this may be solved by #177 if those texture and pbr values are always unique for a given shape in which case it can be fetched from the voxel's parent shape. Else some dedicated functions at voxel level are needed as voxels are not entities (those functions would still be nice for convenience even if not mandatory though).

EDIT: #142 was tracking the pbr part of this issue already, my bad :/

**Comment by Please-Pick-a-Name** [comment] 2022-11-06 09:19
#142 ;-;

**Comment by Please-Pick-a-Name** [comment] 2022-11-06 09:19
tho texture is engine render magic, so you would probably need to use GetEntityProperties for that, since it doesnt actually change the voxel

**Comment by FlorentP42** [comment] 2022-11-06 09:21
Oh I missed yours in the search somehow -_- Well if the completion of both tickets could lead to a solution for this one then all good for me :)

**Comment by FlorentP42** [comment] 2023-03-19 09:33
@tuxedolabs: Any hope for this one? :p

**Comment by Thomasims** [comment] 2023-03-23 12:07
Duplicate of #142

**Closed as completed by Thomasims** 2023-03-23 12:07 UTC
Labels: duplicate, feature request
