### ISSUE TITLE
Credits screen awards "above and beyond".

### ISSUE THREAD

**Issue by MisterFizzy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#248] opened 2022-06-24 15:51 UTC
### Describe the bug

The credits that play after you beat the game, appear to give you the "above and beyond" steam achievement as the moving camera flies above 100m.

### Steps to reproduce the behavior

1. Finish the last mission and enter the credits. Make sure you don't have the "above and beyond" achievement.
2. Wait for the camera to fly above 100m somewhere in the marina.
3. You'll be awarded the above and beyond achievement.

### Expected behavior

The above and beyond achievement shouldn't be rewarded when the camera flies above 100 m, but only when the player themselves travels this far up.

### Environment

Game version: 1.1.0

**Comment by YuLun-bili** [comment] 2024-02-10 00:58
Can't reproduce in latest version (1.5.3). Maybe already patched.

**Comment by YuLun-bili** [comment] 2024-02-10 01:17
Just checked player and camera movement, either reached height above 100m so it won't trigger achievement. Closing.

**Closed as completed by YuLun-bili** 2024-02-10 01:17 UTC
Labels: bug
