### ISSUE TITLE
[Bug] floating objects in Isla Estocastica

### ISSUE THREAD

**Issue by vltr** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#71] opened 2021-12-15 14:39 UTC
### Describe the bug

during the campaign, there was two missions - both in Isla Estocastica - where I was able to make objects to "float". first one was the one that I need to collect some barrels, the second one I was collecting explosives (mostly gas tanks) to explode the "drug dealer's yacht" - you can see that in the screenshots below.

![2021-12-08_10-59](https://user-images.githubusercontent.com/1540275/146205733-7c697d16-6c25-484f-b144-e02f6665cff2.png)

![2021-12-08_10-59_1](https://user-images.githubusercontent.com/1540275/146205764-4d2c69bc-0116-4b12-ad74-d0149db68849.png)

### Steps to reproduce the behavior

1. go to one of the missions in Isla Estocastica
2. grab at least two objects to transport in the elevator (but do not call it, just pile them right next to the shaft)
3. go down, lift the elevator while inside it (it's important not to leave the elevator floor, Idk why)
4. place / drag the objects (barrels or gas tanks) into the elevator
5. use the elevator commands to go down one level
6. you should see the "problem"

### Expected behavior

I believe the objects should follow the elevator's level ... with a simple "touch" in the objects (RMB), they would go down as expected.

### Environment

- Teardown Version: Idk*
- OS: Windows 10
- GPU: Radeon Vega 56
- Graphics driver version: Idk*
- CPU: Ryzen 3900X

* _if relevant I'll take a look and add to the issue_

### Additional context

I had two mods enabled (both distributed by default with the game): odometer and minigun (I can try to reproduce the error without them if needed, just let me know).

**Comment by vltr** [comment] 2021-12-16 10:06
### Updates

the steps to reproduce are correct as I was able to perform the same "error" right now (while testing it without any mods enabled). here's some screenshots:

![2021-12-16_06-34](https://user-images.githubusercontent.com/1540275/146350513-f2266312-0c35-42a2-84a3-70f61d5899df.jpeg)
step 2

![2021-12-16_06-35](https://user-images.githubusercontent.com/1540275/146350547-fabc517f-7cb3-4408-b739-9ce778715b2b.jpeg)
step 3

![2021-12-16_06-35_1](https://user-images.githubusercontent.com/1540275/146350555-7407797f-aa53-4b5a-a8ed-3db8f97276b1.jpeg)
step 3

![2021-12-16_06-36](https://user-images.githubusercontent.com/1540275/146350565-65e6a488-f072-4cb3-bfb0-b823140b7e2e.jpeg)
step 4

![2021-12-16_06-36_1](https://user-images.githubusercontent.com/1540275/146350580-29930a7b-c524-448f-8519-a915275ac127.jpeg)
step 6

![2021-12-16_06-36_2](https://user-images.githubusercontent.com/1540275/146350587-513a4af7-c948-43cc-945f-f4ec71f93171.jpeg)
step 6

it was farily easy to reproduce this, so I don't think all the steps are necessary but that's what I could recall from my missions and could reproduce them (this very morning).

#### Missions affected
* Moving the goods
* Elena's Revenge (the ones in the screenshot)

#### Environment
* Teardown Version: 0.9.0
* Graphics driver version: Radeon 21.10.2

**Comment by tuxedolabs** [comment] 2022-02-07 08:49
Duplicate of internal issue. Will take a look. Thanks for reporting!

**Closed by tuxedolabs** 2022-02-07 08:49 UTC
Labels: bug, dev/in progress, type/engine
