### ISSUE TITLE
[Bug] Unfocusing teardown while its starting breaks audio

### ISSUE THREAD

**Issue by PneumaOfficial** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#306] opened 2022-12-30 18:00 UTC
### Describe the bug

Playing on Windows 10, teardown is up to date.

### Steps to reproduce the behavior

1. Go to steam
2. Click 'Play'
3. Switch focus to any other window
4. Wait a few seconds for teardown to finish starting
5. Go back to teardown
6. No more sound

### Expected behavior

Sound

### Environment

- Teardown Version 1.3.0
- OS: Windows 10
- GPU: GTX 1050ti
- Graphics driver version: Gameready latest version
- CPU: i7

**Comment by PneumaOfficial** [comment] 2022-12-30 18:01
This is a consistent issue btw, haven't reported it until now cuz I figured yall were already on it

**Comment by una-ki** [comment] 2022-12-30 18:03
This is already a known issue, temporary fix is to switch display settings or to not unfocus the game in the first place

**Comment by PneumaOfficial** [comment] 2022-12-31 05:58
> This is already a known issue, temporary fix is to switch display settings or to not unfocus the game in the first place

Has there been a response on why its still remaining a known issue?
That big update came out but this issue persisted through it. Would've thought it got some attention

**Comment by Thomasims** [comment] 2023-03-23 12:42
Duplicate of #292

**Closed as completed by Thomasims** 2023-03-23 12:42 UTC
Labels: bug, duplicate, type/engine

**Comment by IM-DANIL** [comment] 2025-10-03 18:16
=ТЕРПИМ=
