### ISSUE TITLE
[Bug] Game crashes if vehicle is deleted while player inside of it

### ISSUE THREAD

**Issue by MisterSirCode** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#25] opened 2021-04-05 13:31 UTC
**Describe the bug**
If you delete a vehicle while inside of it, it seems it also causes the player to be deleted, which causes the game to instantly crash

**To Reproduce**
1. Open the game
2. Enter a car
3. Delete the car (My mod menu "SirCode's Mod Menu" can delete nearby objects if you need a quick way to delete it)
4. Game will instantly crash

**Expected behavior**
It *should* delete the car and cause the player to just hop out, but instead seems deletes the player itself aswell

**Screenshots / Videos**
As you will see in the video, after deleting the vehicle, the screen goes black and the game crashes. I'm assuming that the game is deleting the player as well as the vehicle, or is at least deleting something important
https://www.youtube.com/watch?v=oWbdjjPVncc

**Environment**
 - Teardown Version: 0.6.2 (patch 1)
 - OS: Windows 10 Pro
 - GPU: MSI NVidia RTX 2070 Super
 - Graphics driver version: GRD 465.89
![image](https://user-images.githubusercontent.com/44554976/113578614-14968d80-95f1-11eb-8cea-db4c6a700c52.png)
 - CPU: Ryzen 7 2700 X

**Additional context**
I used my mod menu to delete the car. It raycasts nearby objects and uses the `Delete(handle)` method on every dynamic object found (including a car)

**Comment by Thomasims** [comment] 2021-04-05 15:49
Duplicate of #7 ?

**Comment by ss-gnalvesteffer** [comment] 2021-04-05 15:51
> Duplicate of #7 ?

Good observation. This seems related, and may be useful to inform the devs about, since the linked issue is being worked on at the moment.

**Comment by MisterSirCode** [comment] 2021-04-05 18:10
> > Duplicate of #7 ?
> 
> Good observation. This seems related, and may be useful to inform the devs about, since the linked issue is being worked on at the moment.
> 
> I don't think it's a duplicate issue though, as this issue describes deleting a vehicle with the player inside to cause a crash, while issue #7 describes that completely destroying a boat causes a crash if the player is inside it. The root cause may likely be the same though, but there's enough difference in the repro steps to warrant keeping this issue open in my opinion.

I think it is a duplicate, since both actually encase the car / vehicle being separated / destroyed / deleted while the player is in it.
Up to you guys really

**Comment by CoolJWB** [comment] 2021-04-08 23:38
This is already in progress as I understand and it appears to be a duplicate of the earlier discussed issue.
However, thanks for the additional information, 👍

**Comment by ss-gnalvesteffer** [comment] 2021-04-09 00:33
Will close this issue since it’s confirmed to be a duplicate. Status will be tracked in #7.

**Closed by ss-gnalvesteffer** 2021-04-09 00:33 UTC
Labels: dev/in progress, duplicate, issue/bug, tag/type-engine
